### ISSUE TITLE
Cannot install Clinica using developper instructions (AttributeError: 'ParsedRequirement' object has no attribute 'req')

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#102]
When following the [developper instructions](http://www.clinica.run/doc/Installation/#developer-installation) on the Wiki, I have the following issue:

```text
$ pip install -e .
Obtaining file:///Users/alexandre.routier/Projects/Git/clinica_t1_linear
    ERROR: Command errored out with exit status 1:
     command: /Users/alexandre.routier/Software/Miniconda3/envs/ClinicaT1Linear/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/alexandre.routier/Projects/Git/clinica_t1_linear/setup.py'"'"'; __file__='"'"'/Users/alexandre.routier/Projects/Git/clinica_t1_linear/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/m_/j76n37kn4vs6zsj8fq0qcgy0000dn9/T/pip-pip-egg-info-ys4r99pq
         cwd: /Users/alexandre.routier/Projects/Git/clinica_t1_linear/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/alexandre.routier/Projects/Git/clinica_t1_linear/setup.py", line 16, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/Users/alexandre.routier/Projects/Git/clinica_t1_linear/setup.py", line 16, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems that we can solve this issue following this example: https://stackoverflow.com/questions/62114945/attributeerror-parsedrequirement-object-has-no-attribute-req

Alex

**Comment by alexandreroutier** [comment]
Solved in PR #104.
