### ISSUE TITLE
Cannot conduct "dwi-preprocessing-using-t1" without using cuda

### ISSUE THREAD

**Issue by felicityshaw** [aramis-lab/clinica#1075]
Hello,

Thanks for your development and sharing of Clinica; it's a very useful tool.

Recently, while attempting the "dwi-preprocessing-using-t1" pipeline without utilizing CUDA, I encountered an unexpected error related to the inability to locate the eddy_corrected file. In an effort to resolve this issue, I referred to solutions for similar issues posted on this git. Following the guidance, I executed the command detailed in the "command.txt" file within the corresponding folder, which initiates with "eddy". Unfortunately, this resulted in a "ValueError: could not convert string to float: ''". Additionally, executing the simple "eddy" command in the terminal was unsuccessful until I substituted "eddy" with "eddy_cpu".

Could you please advise on how to address this issue? Thank you in advance for your assistance.

**Comment by NicolasGensollen** [comment]
Hi @felicityshaw 

Thanks for reporting.
Could you provide a bit more information about your setup and what you were trying to do ? (OS name and version, Python version, Clinica version, what the input data looks like, the command you ran, the error you got when running the pipeline, and the error you got running the command in the `command.txt` file)

**Comment by felicityshaw** [comment]
Sure. 

**OS**: Ubuntu 20.04.6

**Python**: 3.11.6

**Input data**: DWI in BIDS format 

**The command I ran**: 
`clinica run dwi-preprocessing-using-t1 --n_procs 8 -wd wd_copy BIDS_copy CAPS_copy`

**Error I got**:
```
RuntimeError: Traceback (most recent call last):
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node eddy_fsl.

Traceback (most recent call last):
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_corrected' trait of an EddyOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/eddy_fsl/eddy_corrected.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/eddy_fsl/eddy_corrected.nii.gz' for output 'out_corrected' of a Eddy interface
```

**Go to folder**: 
```
/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/eddy_fsl/
```

**Files in this folder**:
![image](https://github.com/aramis-lab/clinica/assets/48397751/bbfe6081-4e52-46a3-9110-6cc08633ec29)

**Content in 'command.txt'**:
```
eddy --flm=quadratic --ff=10.0 --acqp=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/acq.txt --bvals=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.bval --bvecs=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.bvec --imain=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.nii.gz --index=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/index.txt --mask=/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/mask_reference_b0/reference_b0_volume_brain_mask.nii.gz --interp=spline --resamp=jac --niter=5 --nvoxhp=1000 --out=/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/eddy_fsl/eddy_corrected --repol --slm=none
```

**Run the above command directly in the terminal, I got the error**:
```
Traceback (most recent call last):
  File "/home/local/PARTNERS/fsl/bin/eddy", line 98, in <module>
    main()
  File "/home/local/PARTNERS/fsl/bin/eddy", line 79, in main
    eddy_cuda   = find_suitable_eddy_cuda()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/PARTNERS/fsl/bin/eddy", line 58, in find_suitable_eddy_cuda
    eddy_cudas = find_all_eddy_cudas()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/PARTNERS/fsl/bin/eddy", line 48, in find_all_eddy_cudas
    eddy_vers  = [float(op.basename(f)[9:]) for f in eddy_cudas]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/PARTNERS/fsl/bin/eddy", line 48, in <listcomp>
    eddy_vers  = [float(op.basename(f)[9:]) for f in eddy_cudas]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

```
**Replace eddy with eddy_cpu**:
```
eddy_cpu --flm=quadratic --ff=10.0 --acqp=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/acq.txt --bvals=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.bval --bvecs=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.bvec --imain=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/sub-ADNI003S4119_ses-M006_dwi_merged.nii.gz --index=/home/local/PARTNERS/mount_file/BIDS_copy/sub-ADNI003S4119/ses-M006/dwi/index.txt --mask=/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/mask_reference_b0/reference_b0_volume_brain_mask.nii.gz --interp=spline --resamp=jac --niter=5 --nvoxhp=1000 --out=/home/local/PARTNERS/mount_file/wd_copy/dwi-preprocessing-using-t1/eddy_fsl/854443cb478db7cdc37ae2446543b7934a6a857d/eddy_fsl/eddy_corrected --repol --slm=none
```

This revised command works.

**Comment by ghisvail** [comment]
A few questions / remarks:

- Which version of FSL are you running? Looks quite old to me (likely from the 2021 era).
- Based on the traceback, it looks like you're running Clinica with Python version 3.10, not 3.11.

The most recent version of FSL (The conda-based version installed by the fslinstaller) features a different entry-point script which does not have this bug.

**Comment by ghisvail** [comment]
Comparing the [old](https://git.fmrib.ox.ac.uk/fsl/eddy/-/blob/2111.0/eddy?ref_type=tags) to the [new](https://git.fmrib.ox.ac.uk/fsl/eddy/-/blob/2401.1/eddy?ref_type=tags) entry-point.

**Comment by felicityshaw** [comment]
Indeed, I noticed that the version of FSL installed was outdated, and I was using Python version 3.10. After reinstalling FSL with the latest fslinstaller.py available on the FSL website, I attempted the process again but encountered the same error as before.


Besides, when I ran the 't1-freesurfer' pipeline by the following command:
```
clinica run t1-freesurfer -tsv ./tsv/sub-ADNI127S5067.tsv -wd wd_copy BIDS_copy CAPS_copy
```

I got the error traceback like this: 
 
```
Traceback (most recent call last):
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/clinica/pipelines/t1_freesurfer/t1_freesurfer_cli.py", line 73, in cli
    pipeline.run(plugin="MultiProc", plugin_args={"n_procs": n_procs})
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/clinica/pipelines/engine.py", line 353, in run
    raise e
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/clinica/pipelines/engine.py", line 334, in run
    exec_graph = Workflow.run(self, plugin, plugin_args, update_hash)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 166, in run
    self._clean_queue(jobid, graph, result=result)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 244, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/home/local/PARTNERS/anaconda3/envs/clinicaEnv/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node 1-SegmentationReconAll.

RuntimeError: subprocess exited with code 1.
```


I tried adjusting the n_procs value (to 16, 8, 4, and 1) in an attempt to resolve the issue, yet the problem persisted. Are there specific CPU resource requirements that "nipype" or "multiprocs" necessitates?

**Comment by NicolasGensollen** [comment]
Hi @felicityshaw 

The issue is starting to be difficult to follow.
The initial post is about an issue in the `DWIPreprocessingUsingT1` pipeline which seems to be linked with the installed version of FSL. Reading your message above, I understand that you were able to install a newer version of FSL. What version did you install ? When you run the DWI pipeline, what error are you getting now ? The exact same one as before ? What happens when you run manually the eddy command in your terminal ?

 For the problem with the `T1Freesurfer` pipeline, I don't think it is related since the underlying executable is the FreeSurfer `recon-all`. What version of Freesurfer do you have installed on your system ? Are you able to run things like `recon-all --help` in your terminal ? If yes, could you locate the command which crashed the pipeline and try to run it directly ?

**Comment by NicolasGensollen** [comment]
Hi @ta4218 

Thanks for reporting. First of all, what version of Clinica are you using ? If in the `0.7.X` series, it might be worth trying with the recently released `v.0.8.0` which changed a few things in the DWI pipelines.

Moreover, have you tried running the eddy command in your terminal ?
Have you checked that the different input files exist ?
Have you checked in the full traceback if you had an error before the `eddy_fsl` node (which could explain that some expected files by downstream nodes are not present) ?
