### ISSUE TITLE
Problem when use multiple -m modalities covert ADNI data

### ISSUE THREAD

**Issue by ziqian1215** [aramis-lab/clinica#1291]
**Description**
When I use this command to convert one subject,
$ clinica convert adni-to-bids /path/to/adni_data /path/to/clinical_data /path/to/output_bids --xml_path /path/to/adni_metadata -m T1 -m DWI -m fMRI
There is something wrong with traceback:

Traceback (most recent call last):
  File "/nas/longleaf/home/ziqian1/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'APGEN1'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 7
9, in cli
    adni_to_bids.convert_clinical_data(
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 123, 
in convert_clinical_data
    participants_df = bids.create_participants_df(
  File "/nas/longleaf/home/ziqian1/anaconda2/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/bids_utils.py", line 125, in create_participants_df
    value_to_read = file_to_read[participant_fields_db[i]]
  File "/nas/longleaf/home/ziqian1/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/nas/longleaf/home/ziqian1/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'APGEN1'

While the bids output looks ok, just lacks validator.json. What is the reason for this error?

**Converters**
Which Clinica's converter is concerned?
- adni-to-bids

Thanks!
<img width="526" alt="Screenshot 2024-09-09 at 10 56 15 PM" src="https://github.com/user-attachments/assets/6234d6c0-d977-497f-8ed4-cf2066830541">

**Comment by souravraha** [comment]
I get this even with a single `-m` flag. I didn't know that it produces (almost) correct BIDS directory. Thanks for pointing that out.

**Comment by AliceJoubert** [comment]
Hi, thanks for the clarification !

First, I would advise to use a new python environment with the latest clinica release since we are currently working with python 3.10 and clinica v0.8.4 (you have the instructions for downloading [here](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/)). 

Second, I suspect an issue with the --xml option that I will need to see into. The error you get happens when the converter tries to create metadata files using the .xml you provided. You might still have the same kind of error even when downloading the latest version of clinica, so do not hesitate to tell me if so. In case the .xml metadata is not that important to you you can run the converter without while we fix this. 

Also, clinica does not support ADNI 4 yet so errors are expected to happen if using it in this manner. 

For your question about image type : 
If you plan to preprocess the images, does that mean they would be in nifti after this ? If they stay in dicom format you can maybe use clinica but in adni-to-bids there is a selection based on a quality check provided in the study csv files (read more about this [here](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/#advanced-appendix-how-adni-is-converting-into-bids)). As such I am unsure you would get what you expect as an output. If you just want to get a BIDS (no conversion) after preprocessing you can still look up heudiconv, dcm2bids or ezBIDS.

Do not hesitate if you have any other issue !

Best,

**Comment by ziqian1215** [comment]
Hi there,

Thank you for your detailed instructions! I have trid use python 3.10 and clinica v0.8.4 to reprocess, and when I use -c to convert only clinical data, there is still show the KeyError: 'APGEN1' issues when creating participants.tsv.
used command, without -xml:
$ clinica convert adni-to-bids /path/to/adni_data /path/to/clinical_data /path/to/output_bids -m T1 -m DWI -m fMRI -c
<img width="1433" alt="Screenshot 2024-09-12 at 7 19 44 PM" src="https://github.com/user-attachments/assets/bd038397-97a0-4494-98dc-eaa2e69e9170">

And when I use subjects_lists.txt try to extract the clinical information, it shows:
<img width="1433" alt="Screenshot 2024-09-12 at 7 23 53 PM" src="https://github.com/user-attachments/assets/0940d1de-fb7e-494a-92ce-96edb22334f6">

Here is the .txt file content:
<img width="725" alt="Screenshot 2024-09-12 at 7 25 45 PM" src="https://github.com/user-attachments/assets/4d8de95c-3f63-4f2f-a1fb-710efd4b52af">

For now, I think the issue is only for processing participants.tsv.

Thanks!

**Comment by AliceJoubert** [comment]
Hello !

Thanks for the precisions. The issue indeed only occurs when trying to build the participants.tsv. I am adding this to our to-do list but I don't know if a fix of this will be released soon. I hope you can work with what the converter gives you for now ! Don't hesitate if you see something else,

Best,

Alice
