### ISSUE TITLE
dwi-preprocessing :problem reading coef-file out_warp.nii.gz : blank image about the out_warp.nii.gz

### ISSUE THREAD

**Issue by asd567** [aramis-lab/clinica#248]
Hi, there!

I used the command `clinica convert adni-to-bids ADNI clinicaData BIDS  -m T1 DWI` , and the command `clinica iotools center-nifti BIDS BIDS1 --modality "t1w dwi"  ` .  This two commands have run successfully.  Then I began to run `dwi-preprocessing-using-t1`  , but some errors happened: CAPS outputs were not found for some image(s) . 

 I looked at the crashed file and the output informations as follows:

File: /media/limpid/T7/LMCI/crash-20210521-145156-limpid-CoeffComp.a1-8a020d2f-bb8a-474a-8113-19d1f1c867e7.pklz
Node: dwi-preprocessing-using-t1.SusceptibilityDistortionCorrection.CoeffComp
Working directory: /tmp/tmpevvxw26l/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/3550caa6574f05f6ba2e85e572e66d9c72daedc2/CoeffComp

Node inputs:

args = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
in_file = <undefined>
knot_space = <undefined>
out_file = <undefined>
out_format = spline
out_jacobian = <undefined>
output_type = NIFTI_GZ
reference = /media/limpid/T7/LMCI/BIDS/sub-ADNI002S4229/ses-M72/anat/sub-ADNI002S4229_ses-M72_T1w.nii.gz
warp_resolution = <undefined>
with_affine = <undefined>
write_jacobian = False

Traceback: 
Traceback (most recent call last):
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
fnirtfileutils --in=/tmp/tmpevvxw26l/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/3550caa6574f05f6ba2e85e572e66d9c72daedc2/combine_warp/out_warp.nii.gz --outformat=spline --ref=/media/limpid/T7/LMCI/BIDS/sub-ADNI002S4229/ses-M72/anat/sub-ADNI002S4229_ses-M72_T1w.nii.gz --out=out_warp_coeffs.nii.gz
Standard output:

Standard error:
fnirtfileutils: Problem reading coef-file /tmp/tmpevvxw26l/dwi-preprocessing-using-t1/SusceptibilityDistortionCorrection/3550caa6574f05f6ba2e85e572e66d9c72daedc2/combine_warp/out_warp.nii.gz
Return code: 1

My fsl-version is 6.0.4, and I fixed the problem about FSLeyes.  I used the command 'fsleyes out_warp.nii.gz',and found that the image is blank.  

Does anyone have any idea to fix this problem?

Thanks

**Comment by asd567** [comment]
I solved this problem in the google-groups-clinica , I am closed this issue.
