### ISSUE TITLE
dwi-dti error : caps outputs were not found for some image(s):RuntimeError: Mismatch in number of expected outputs

### ISSUE THREAD

**Issue by asd567** [aramis-lab/clinica#250]
command : 'clinica run dwi-dti CAPS'
The pipeline will last approximately 20 minutes per image.
19

[Warning] You did not specify the number of threads to run in parallel (--n_procs argument).
Computation time can be shorten as you have 20 CPUs on this computer. We recommend using 19 threads.

How many threads do you want to use? If you do not answer within 15 sec, default value of 19 will be taken. Use --n_procs argument if you want to disable this message next time.
[19:51:33] Running pipeline for sub-ADNI002S4654 | ses-M60
[19:51:34] Running pipeline for sub-ADNI002S4654 | ses-M72

[19:51:37] Pipeline finished with errors.

CAPS outputs were not found for some image(s):
Implementation on which image(s) failed will appear soon.

Documentation can be found here: https://aramislab.paris.inria.fr/clinica/docs/public/latest/
If you need support, do not hesitate to ask: https://groups.google.com/forum/#!forum/clinica-user
Alternatively, you can also open an issue on GitHub: https://github.com/aramis-lab/clinica/issues

crash file outputs:

File: /media/limpid/T7/LMCI_4654/crash-20210521-195135-limpid-0-CAPS_Filenames.a1-1f29f213-b65f-4547-842e-d46546d0166a.pklz
Node: dwi-dti.0-CAPS_Filenames
Working directory: /tmp/tmpsny4ks55/dwi-dti/d85a643f4505ec233847dc5ab60eb39aeab71843/0-CAPS_Filenames

Node inputs:

caps_dwi_filename = /media/limpid/T7/LMCI_4654/CAPS/subjects/sub-ADNI002S4654/ses-M72/dwi/preprocessing/sub-ADNI002S4654_ses-M72_acq-axial_dwi_space-T1w_preproc.nii.gz
function_str = def get_caps_filenames(caps_dwi_filename):
    Prepare some filenames with CAPS naming convention.
    import re

    m = re.search(
        r"(sub-[a-zA-Z0-9]+)_(ses-[a-zA-Z0-9]+).*_dwi_space-[a-zA-Z0-9]+",
        caps_dwi_filename,
    )
    if m is None:
        raise ValueError("Input filename is not in a CAPS compliant format.")

    caps_prefix = m.group(0)
    bids_source = f"{m.group(1)}_{m.group(2)}_dwi"

    out_dti = f"{caps_prefix}_model-DTI_diffmodel.nii.gz"
    out_fa = f"{caps_prefix}_FA.nii.gz"
    out_md = f"{caps_prefix}_MD.nii.gz"
    out_ad = f"{caps_prefix}_AD.nii.gz"
    out_rd = f"{caps_prefix}_RD.nii.gz"

    return bids_source, out_dti, out_fa, out_md, out_ad, out_rd

Traceback: 
Traceback (most recent call last):
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 147, in _run_interface
    raise RuntimeError("Mismatch in number of expected outputs")
RuntimeError: Mismatch in number of expected outputs

Does anyone have any opinion?
Thanks

**Comment by asd567** [comment]
I add some informations in the wrap.py, and here are the outputs 

Traceback: 
Traceback (most recent call last):
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/limpid/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 147, in _run_interface
    raise RuntimeError("Mismatch in number of expected outputs "+ str(len(out))+ str(out) + " " + str(len(self._output_names))+ str(self._output_names) )
RuntimeError: Mismatch in number of expected outputs 6('sub-ADNI002S4654_ses-M60_dwi', 'sub-ADNI002S4654_ses-M60_acq-axial_dwi_space-T1w_model-DTI_diffmodel.nii.gz', 'sub-ADNI002S4654_ses-M60_acq-axial_dwi_space-T1w_FA.nii.gz', 'sub-ADNI002S4654_ses-M60_acq-axial_dwi_space-T1w_MD.nii.gz', 'sub-ADNI002S4654_ses-M60_acq-axial_dwi_space-T1w_AD.nii.gz', 'sub-ADNI002S4654_ses-M60_acq-axial_dwi_space-T1w_RD.nii.gz') 7['bids_source', 'out_dti', 'out_fa', 'out_md', 'out_ad', 'out_rd', 'out_evec']

**Comment by asd567** [comment]
Oh, I changed the environment about fsl and now it's ok. This issue should be written in the document.
