### ISSUE TITLE
Silent Tracebacks for ClinicaException

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinica#361]
**Describe the bug**
In previous versions of Clinica, when a subclass of `ClinicaException` was raised, the Python traceback was not displayed. Now, we have:

```Text
Traceback (most recent call last):
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/bin/clinica", line 33, in <module>
    sys.exit(load_entry_point('clinica', 'console_scripts', 'clinica')())
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/ClinicaDwi/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/pipelines/dwi_preprocessing_using_t1/dwi_preprocessing_using_t1_cli.py", line 59, in cli
    if n_procs
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/pipelines/engine.py", line 266, in run
    self.build()
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/pipelines/engine.py", line 27, in func_wrapper
    res = func(self, *args, **kwargs)
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/pipelines/engine.py", line 233, in build
    self.check_dependencies()
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/pipelines/engine.py", line 369, in check_dependencies
    check_software[d["name"]](d["version"])
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/utils/check_dependency.py", line 160, in check_mrtrix
    check_environment_variable("MRTRIX_HOME", "MRtrix")
  File "/Users/alexandre.routier/Projects/Git/clinica_fork/clinica/utils/check_dependency.py", line 51, in check_environment_variable
    f"The {environment_variable} environment variable "
clinica.utils.exceptions.ClinicaMissingDependencyError: The MRTRIX_HOME environment variable you gave is not a folder (content: /Users/alexandre.routier/Software/mrtrix3_latest).
```

For known errors (using `ClinicaException` subclass), could the previous behaviour be restored? This would make error message more understable.

**Comment by ghisvail** [comment]
> the Python traceback was not displayed

What's the rationales for silencing them? Looking at your sample traceback, it's easy to figure out what's going on.

Exception subclasses that remove information really sounds like a bad idea, especially in a dynamic language like Python.

**Comment by alexandreroutier** [comment]
This was for user-friendly CLI purposes. Any `ClinicaException` raised by the terminal corresponds to known error with self explanations. In this example, only the line:
```Text
clinica.utils.exceptions.ClinicaMissingDependencyError: The MRTRIX_HOME environment variable you gave is not a folder (content: /Users/alexandre.routier/Software/mrtrix3_latest).
```
is relevant.

This is quite similar of MRtrix software (mixing C++ & Python).
