### ISSUE TITLE
adni-to-bids: ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by m-petersen** [aramis-lab/clinica#379]
**Description**
What is happening?

I want to convert ADNI to BIDS with the clinica converter. For that I followed the instructions provided in the documentation (https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/) with the imaging data in one directory, the clinical data in another. Since I want to use dcm2niix for conversion I installed the latest release from git with pip "pip install git+https://github.com/aramis-lab/clinica". Running `clinica convert adni-to-bids <imaging_directory> <clinical_directory> <bids_output>` results in 

`
/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py:67: DtypeWarning: Columns (18,19,20,102,103,104) have mixed types.Specify dtype option on import or set low_memory=False.
  force_new_extraction,
Traceback (most recent call last):
  File "/work/fatx405/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/cmdline.py", line 78, in main
    cli()
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 67, in cli
    force_new_extraction,
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 198, in convert_images
    force_new_extraction,
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py", line 34, in convert_adni_t1
    images = compute_t1_paths(source_dir, csv_dir, dest_dir, subjs_list, conversion_dir)
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_modalities/adni_t1.py", line 111, in compute_t1_paths
    subj, mprage_meta_subj, adnimerge_subj, "T1", "Visit", "ScanDate"
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 62, in visits_to_timepoints
    image, pending_timepoints, subject, visit_field, scandate_field
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 151, in get_closest_visit
    if not min_visit:
  File "/work/fatx405/miniconda3/envs/clinicaEnv/lib/python3.7/site-packages/pandas/core/generic.py", line 1535, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`

Grateful for any input.

Cheers,
Marvin

**Converters**
Which Clinica's converter is concerned ?
E.g.
- adni-2-bids

**Comment by ghisvail** [comment]
The actual error is at then end: `ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()`
