### ISSUE TITLE
Error using dwi-preprocessing-using-fieldmap

### ISSUE THREAD

**Issue by eburkevt** [aramis-lab/clinica#453]
I'm running Clinica v0.3.7, with 
ANTs v2.3.5
FSL v6.0.3
convert3d

**Describe the bug**

Error running dwi-preprocessing-using-fieldmap. 

The error messages are (mica is the name of our server)

"CAPS outputs were not found for some image(s):"

AND

	 "[Node] Error on "dwi-preprocessing-using-fieldmap.SusceptibilityDistortionCorrection.FmapMagnitudeToB0" (/net/storage1/usr2/onrc/home/Chyatt/onrc/data/clinica/work/dwi-preprocessing-using-fieldmap/SusceptibilityDistortionCorrection/06a55a638f5df66ab5ffdb7d139b2faf9bd16230/FmapMagnitudeToB0)
211002-13:41:52,717 nipype.workflow ERROR:
	 Node FmapMagnitudeToB0.a0 failed to run on host mica."

I attached the crash file.

**To Reproduce**

Here's the call to clinica I used (low_bval is set to 5, because bvals lowest value is 5, not 0)

clinica run dwi-preprocessing-using-fieldmap \
	${basefolder}/tmsautism \
	${basefolder}/tmsautism/derivatives/clinica \
	--low_bval 5 \
	--n_procs 12 \
	-tsv subjlist.tsv \
	-wd ${basefolder}/work | tee clinica.log

My input DWI images (all BIDs formatted) are LR phase encoded, with 2 magnitude and 1 phase diff field maps as "intended for" the DWI images for susceptibility distortion correction (I also had somewhat similar problems with 'dwi-preprocessing-using-t1', but prefer to use field maps).

**Expected behavior**
No crashing.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux 64bit
 - Browser N/A
 - Version CentOS 7.5

**Additional context**
It ran fine up until the 'FmapMagnitudeToB0' problem. 

I tried a number of things, including upgrading to Clinica v0.5.1, changing FSL version from 6.0.3 to 5.0.11. Nothing worked
I attached the crash file (running Clinica v0.3.7 and FSL 6.0.3)

[crash-20211002-134152-Chyatt-FmapMagnitudeToB0.a0-2aff33bc-bec6-4d65-9a10-47b2aee2b4c1.zip](https://github.com/aramis-lab/clinica/files/7272268/crash-20211002-134152-Chyatt-FmapMagnitudeToB0.a0-2aff33bc-bec6-4d65-9a10-47b2aee2b4c1.zip)
.

**Comment by alexandreroutier** [comment]
Hello @eburkevt,

Thanks for you interest in Clinica.

The `crash-20211002-134152-Chyatt-FmapMagnitudeToB0.a0-2aff33bc-bec6-4d65-9a10-47b2aee2b4c1.zip` cannot be opened when running:
```Text
nipypecli crash crash-20211002-134152-Chyatt-FmapMagnitudeToB0.a0-2aff33bc-bec6-4d65-9a10-47b2aee2b4c1.zip
```
Usually, the crash files have `*.pklz` extension. Coud you provide the `*.pklz` file copy/paste the result of the command?

On top of that, the `FmapMagnitudeToB0` node invokes `antsRegistration` from ANTs. To my knowledge, ANTs v2.3.5 was never tested with Clinica and sub-pipelines using latest ANTs version. Could you try with ANTs 2.3.1 as indicated on the [documentation](https://aramislab.paris.inria.fr/clinica/docs/public/latest/Third-party/)?

For curiosity, what crash file was generated when running the `dwi-preprocessing-using-t1` pipeline?

Best,
Alexandre

**Comment by eburkevt** [comment]
The pklz file is inside the zip file. I'll downgrade ANTs to 2.3.1 and try again. Thanks.

**Comment by alexandreroutier** [comment]
Indeed, I don't know why but I had to use `unzip` command to get the `pklz` file, otherwise Finder on macOS generated a crash file withouth file extension and could not open it.

The error raised the crash file is new to me:

```Text
211003-19:05:29,55 nipype.utils WARNING:
	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
Traceback (most recent call last):
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/bin/nipypecli", line 8, in <module>
    sys.exit(cli())
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/scripts/cli.py", line 96, in crash
    display_crash_file(crashfile, rerun, debug, dir)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/scripts/crash_files.py", line 51, in display_crash_file
    crash_data = loadcrash(crashfile)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 595, in loadcrash
    return loadpkl(infile)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 668, in loadpkl
    raise e
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 645, in loadpkl
    unpkl = pickle.loads(pkl_contents)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/has_traits.py", line 1341, in __setstate__
    self.trait_set(trait_change_notify=trait_change_notify, **state)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/has_traits.py", line 1434, in trait_set
    setattr(self, name, value)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/trait_types.py", line 2515, in validate
    return TraitListObject(self, object, name, value)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/trait_list_object.py", line 585, in __init__
    notifiers=[self.notifier],
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 134, in validate
    if not value.exists():
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/pathlib.py", line 1361, in exists
    self.stat()
  File "/Users/alexandre.routier/Software/Miniconda3/envs/Nipype1.6.0/lib/python3.7/pathlib.py", line 1183, in stat
    return self._accessor.stat(self)
TimeoutError: [Errno 60] Operation timed out: '/net/storage1/usr2/onrc/home/Chyatt/onrc/data/clinica/work/dwi-preprocessing-using-fieldmap/SusceptibilityDistortionCorrection/06a55a638f5df66ab5ffdb7d139b2faf9bd16230/GetB0/merged_files_eccorrect_roi.nii.gz'
```

Could you test locally the pipeline locally? Besides, could you tell us if `*FmapMagnitudeToB0*` is present on all the crash files or if other nodes names were mentioned in the crash files?

Best

**Comment by ghisvail** [comment]
It would be more helpful to triage this issue with the latest release of Clinica (version 0.5.1 at this time).

**Comment by eburkevt** [comment]
I checked out and compiled ANTs ver. 2.3.1 but it's still showing v2.2.0.  I don't really have time to test this out and further. Thanks.

**Comment by eburkevt** [comment]
I did get the dwi-preprocessing-using-phasediff-fieldmap pipeline to run successfully.
I had to revert to v2.1.0 of ANTs (circa 2015). I tried v2.2.0 and higher, but none of these worked.

However, running the dwi-dti on the output from the dwi-preprocessing-using-phasediff-fieldmap pipeline
(the output is in ${basefolder}/tmsautism/derivatives/clinica/subjects/sub-S6581DHW/ses-01/dwi/preprocessing/)

clinica run dwi-dti \
	${basefolder}/tmsautism/derivatives/clinica \
	--n_procs 12 \
	-tsv subjlist.tsv \
	-wd /home/Chyatt/onrc/data/clinica/work

does not work. I'm running clinica v0.5.1

The crash file contains the following

File: /net/storage1/usr2/onrc/home/Chyatt/onrc/data/clinica/crash-20211005-140442-Chyatt-0-CAPS_Filenames.a0-dec16b96-9458-4b32-b61d-677aa2c58d83.pklz
Node: dwi-dti.0-CAPS_Filenames
Working directory: /net/storage1/usr2/onrc/home/Chyatt/onrc/data/clinica/work/dwi-dti/5f9996be76e998464c5da7d295ef6002d7f3ec6f/0-CAPS_Filenames


Node inputs:

caps_dwi_filename = /net/storage1/usr2/onrc/home/Chyatt/onrc/data/clinica/tmsautism/derivatives/clinica/subjects/sub-S6581DHW/ses-01/dwi/preprocessing/sub-S6581DHW_ses-01_acq-dir91LR_dwi_space-b0_preproc.nii.gz
function_str = def get_caps_filenames(caps_dwi_filename: str):
    """Prepare some filenames with CAPS naming convention."""
    import re

    m = re.search(
        r"(sub-[a-zA-Z0-9]+)_(ses-[a-zA-Z0-9]+).*_dwi_space-[a-zA-Z0-9]+",
        caps_dwi_filename,
    )
    if not m:
        raise ValueError(f"Input filename {caps_dwi_filename} is not in a CAPS compliant format.")

    caps_prefix = m.group(0)
    bids_source = f"{m.group(1)}_{m.group(2)}_dwi"

    out_dti = f"{caps_prefix}_model-DTI_diffmodel.nii.gz"
    out_fa = f"{caps_prefix}_FA.nii.gz"
    out_md = f"{caps_prefix}_MD.nii.gz"
    out_ad = f"{caps_prefix}_AD.nii.gz"
    out_rd = f"{caps_prefix}_RD.nii.gz"

    return bids_source, out_dti, out_fa, out_md, out_ad, out_rd


Traceback: 
Traceback (most recent call last):
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/home/Chyatt/.conda/envs/clinicaEnv/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 147, in _run_interface
    raise RuntimeError("Mismatch in number of expected outputs")
RuntimeError: Mismatch in number of expected outputs



The caps_dwi_filename is correct. The dwi preprocessed output looks okay. Any ideas?

**Comment by alexandreroutier** [comment]
> I did get the dwi-preprocessing-using-phasediff-fieldmap pipeline to run successfully. I had to revert to v2.1.0 of ANTs (circa 2015). I tried v2.2.0 and higher, but none of these worked.

Thanks for the feedback! Please note that versions of `dwi-preprocessing*` are prepared in PR #346. They all use  `eddy` tool [(Andersson et al., 2016)](https://dx.doi.org/10.1016%2Fj.neuroimage.2015.10.019) from FSL to improve quality of preprocessing. `eddy` also adds outlier replacement.

> 
> However, running the dwi-dti on the output from the dwi-preprocessing-using-phasediff-fieldmap pipeline (the output is in ${basefolder}/tmsautism/derivatives/clinica/subjects/sub-S6581DHW/ses-01/dwi/preprocessing/)
> 
> clinica run dwi-dti ${basefolder}/tmsautism/derivatives/clinica --n_procs 12 -tsv subjlist.tsv -wd /home/Chyatt/onrc/data/clinica/work
> 
> does not work. I'm running clinica v0.5.1
> 


I think I found it! In `dwi_dti_utils.py`, you need to add `out_evec` which for unknown reasons is missing:

```python
    out_md = f"{caps_prefix}_MD.nii.gz"
    out_ad = f"{caps_prefix}_AD.nii.gz"
    out_rd = f"{caps_prefix}_RD.nii.gz"
    out_evec = f"{caps_prefix}_DECFA.nii.gz"

    return bids_source, out_dti, out_fa, out_md, out_ad, out_rd, out_evec
```
(this bugfix is in PR #346 for info).

Please let me know if this solve your issue.

Best,
Alex

**Comment by alexandreroutier** [comment]
Based on this message:

```text
NameError: name 'Optional' is not defined
```

I would believe that the annotation `Optional` is not recognised somehow by Nipype.

Could you replace:
```python
def statistics_on_atlases(in_registered_map: str, name_map: str, prefix_file: Optional[str] = None):
```
by:
```python
def statistics_on_atlases(in_registered_map: str, name_map: str, prefix_file: str = None):
```
and tell us if this solves you issue?

I am poking @omar-rifai , @mdiazmel and @ghisvail if they already have this type of error.

**Comment by ghisvail** [comment]
@alexandreroutier is correct. @MatthieuJoulot and myself recently had the same issue and solved it by dropping usage of type hints for functions used in nipype nodes.

`Functions in connection strings have to be standalone` applies to function signatures as well, so any argument requiring the `typing` module (such as `Optional`) breaks this rule.

**Comment by omar-rifai** [comment]
Typing has been introduced on this pipeline on a [commit]((https://github.com/aramis-lab/clinica/pull/373/commits/f26792df32f2700e48226a4681a544de18066aa9) in v0.5.0. @ghisvail, can you please revert the changes introduced that have this side effect? 

We can make a release by the end of the week with the fixes and the new version of dwi-dti-preprocessing

**Comment by eburkevt** [comment]
This appears to have solved the issue. Thanks!
