### ISSUE TITLE
Issue: error !clinica convert oasis3-to-bids Oasis3test Oasis3test/ClinicalData Oasis3BidsRun

### ISSUE THREAD

**Issue by SonaLily** [aramis-lab/clinica#458]
I got error when I do:
!clinica convert oasis3-to-bids Oasis3test Oasis3test/ClinicalData Oasis3BidsRun

 File "/usr/local/lib/python3.7/dist-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py", line 47, in find_clinical_data
    raise FileNotFoundError("Clinical data not found or incomplete")
FileNotFoundError: Clinical data not found or incomplete

I do have this file in Oasis3test/ClinicalData: ADRCclinicalData.csv which I downloaded from xnat. 
**My question is:** Is any special requirement on this file? is it possible you can provide an file with correct format?

I  also tried to dowdload Bids directly from xnat and tried to process those data by:

!clinica run t1-linear Oasis3BIDStest Oasis3Cap --n_procs  2
I got following message:
2021-10-10 12:13:47,002:WARNING:Could not determine if /content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3Cap is a CAPS or BIDS directory. Clinica will assume this is a CAPS directory.
2021-10-10 12:13:50,102:ERROR:Clinica faced error(s) while trying to read files in your BIDS directory.
Clinica encountered 4 problem(s) while getting T1w MRI:
	*  (sub-OAS30001 | ses-d0129): More than 1 file found:
		/content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3BIDStest/sub-OAS30001/ses-d0129/anat/sub-OAS30001_ses-d0129_run-01_T1w.nii.gz
		/content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3BIDStest/sub-OAS30001/ses-d0129/anat/sub-OAS30001_ses-d0129_run-02_T1w.nii.gz
	*  (sub-OAS30001 | ses-d0757): More than 1 file found

**My question is:** is it possible to process bids files downloaded directly from Oasis3  by clinica? if yes, how to do?

Thanks a lot

**Comment by SonaLily** [comment]
I believe I follow the documentation exactly, and I got following error message when I ran:

!clinica convert oasis3-to-bids Oasis3test Oasis3test/Oasis3Clinical101121 Oasis3BidsRun

Traceback (most recent call last):
  File "/usr/local/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/clinica/cmdline.py", line 78, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids_cli.py", line 28, in cli
    convert_images(dataset_directory, bids_directory, clinical_data_directory)
  File "/usr/local/lib/python3.6/site-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_to_bids.py", line 43, in convert_images
    dataset_directory=path_to_dataset,
  File "/usr/local/lib/python3.6/site-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py", line 314, in write_bids
    write_to_tsv(participants, participant_file)
  File "/usr/local/lib/python3.6/site-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py", line 265, in write_to_tsv
    dataframe.to_csv(buffer, sep="\t", na_rep="n/a", date_format="%Y-%m-%d")
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 206, in save
    self._save()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 314, in _save
    self._save_header()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 283, in _save_header
    writer.writerow(encoded_labels)
**TypeError: a bytes-like object is required, not 'str'**

Any suggestion? Please help!!!

**Comment by SonaLily** [comment]
Thank you so much for your help! Fortunately after setting my python environment to 3.7 through your suggestion, I was able to successfully run !clinica convert oasis3-to-bids and !clinica run t1-linear.

Unfortunately, when I ran the following command
!clinica run deeplearning-prepare-data xnatAii/d1capout t1-linear image

I got another error that wasn't there a week ago:
The error message:
 Error: Usage: clinica run [OPTIONS] COMMAND [ARGS]...
Try 'clinica run -h' for help.
Error: No such command 'deeplearning-prepare-data'.


What command should I use to get it working again? 


As a side note, I found that my google colab environment was originally at python 3.7 but because I ran the command-
!pip install clinicadl==0.2.1
!/bin/bash -c "$(curl -k https://aramislab.paris.inria.fr/files/software/scripts/install_conda_ants.sh)"
 -it would convert it to python 3.6, so I ended up skipping that installation step.
Again, thank you so much, this definitely saved me another week of debugging this issue!

**Comment by omar-rifai** [comment]
Hi @SonaLily, 
We have recently migrated the pipeline `deeplearning-prepare-data`to our sister project [`ClinicaDL`](https://github.com/aramis-lab/clinicadl) which handles everything related to deep-learning. The command there has change its name to [`extract`](https://clinicadl.readthedocs.io/en/stable/Preprocessing/Extract/). 
Regards

**Comment by ghisvail** [comment]
> Thank you so much for your help! Fortunately after setting my python environment to 3.7 through your suggestion, I was able to successfully run !clinica convert oasis3-to-bids and !clinica run t1-linear.

I am glad you got it worked out 👍 

Please follow @omar-rifai advice for the transition to `clinicadl`.
