### ISSUE TITLE
Error with adni-to-bids

### ISSUE THREAD

**Issue by sty11111112** [aramis-lab/clinica#632]
What is happening?

This is the first time for my team and me to use the clinica.

We have downloaded sMRI baseline data from ADNI（When I downloaded data from ADNI, I choosed ADNI Baseline, ADNIGO Screening MRI ADNI2 Screening MRI-New Pt and ADNI3 Initial Visit-Cont Pt）and try to get data from baseline. 

We encountered an error while running `clinica convert adni-to-bids $ADNI_PATH $CLINICAL_DATA_DIRECTORY $BIDS --modalities T1`
```
2022-03-31 16:10:08,969:INFO:	Reading clinical data file: VITALS.csv
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 70, in cli
    adni_to_bids.convert_clinical_data(
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 126, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 720, in create_adni_sessions_dict
    df_subj_session = df_subj_session[
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/core/frame.py", line 3495, in __getitem__
    if com.is_bool_indexer(key):
  File "/home/dell/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/core/common.py", line 144, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
```
When I go to the `adni_utils.py`, it shows

```
    # Nv/None refer to sessions whose session is undefined. "sc" is the screening session with unreliable (incomplete)
    # data.
    df_subj_session = df_subj_session[
        df_subj_session.session_id.str.contains("ses-M\d+")
    ]
```
Should I download more data  or do something else to avoid the error?

Hopefully to receive the reply

Thanks.

**Comment by omar-rifai** [comment]
Hi @sty11111112, 

It seems that some of the `sessions_ids` in the clinical data file `VITALS.csv` are `NaN` values. Unfortunately this causes the error you are receiving. The code  in `adni_utils.py`  should read as follows to avoid this error:

```
df_subj_session.session_id.str.contains("ses-M\d+", na=False)
```

I will do a quick fix to avoid this error which should be released by the end of the week.

Regards,

**Comment by sty11111112** [comment]
Thanks for your reply.

I modify the file and solved this problem. 

Thanks again for your helpful reply.

**Comment by ghisvail** [comment]
I am reopening this issue to have it closed once the fix lands in the code.

**Comment by omar-rifai** [comment]
Glad it worked ! 

Regards
