### ISSUE TITLE
cannot execute `t1-volume-register-dartel`

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinica#707]
**Describe the bug**
Cannot execute `t1-volume-register-dartel`

**To Reproduce**
clinica run t1-volume-register-dartel -np 1 -tsv ~/debug/test.tsv ~/data/adni/bids ~/data/adni/caps/ adni2021

Content of test.tsv:
```
	participant_id	session_id
0	sub-ADNI002S2010	ses-M00
```

**Traceback**
2022-07-21 14:37:23,693:INFO:The pipeline will be run on the following 1 image(s):
2022-07-21 14:37:23,693:INFO:	sub-ADNI002S2010 | ses-M00,
Traceback (most recent call last):
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thibeaue/miniconda3/envs/clinica_env/bin/clinica", line 5, in <module>
    main()
  File "/home/thibeaue/code/clinica/clinica/cmdline.py", line 89, in main
    cli()
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/thibeaue/code/clinica/clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_cli.py", line 53, in cli
    pipeline.run(plugin="MultiProc", plugin_args={"n_procs": n_procs})
  File "/home/thibeaue/code/clinica/clinica/pipelines/engine.py", line 269, in run
    exec_graph = Workflow.run(self, plugin, plugin_args, update_hash)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 628, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 967, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 847, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 875, in _remove_identity_node
    _propagate_root_output(graph, node, field, connections)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 914, in _propagate_root_output
    destnode.set_input(inport, value)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 309, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/home/thibeaue/miniconda3/envs/clinica_env/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'in_file' trait of a GunzipInputSpec instance must be a pathlike object or string representing an existing file, but a value of "['/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-1_template.nii.gz', '/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-2_template.nii.gz', '/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-3_template.nii.gz', '/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-4_template.nii.gz', '/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-5_template.nii.gz', '/home/thibeaue/data/adni/caps/groups/group-adni2021/t1/group-adni2021_iteration-6_template.nii.gz']" <class 'str'> was specified.

**Desktop (please complete the following information):**
Linux version 5.4.0-105-generic (buildd@lcy02-amd64-066) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04)) #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022

**Comment by omar-rifai** [comment]
Hello @14thibea, thanks for bringing this up. It looks like the custom unzip_nii utiliy we had was able to handle lists as inputs but we lost this behavior when switching to thethe [Gunzip Interface](https://github.com/aramis-lab/clinica/pull/656/files).

**Comment by 14thibea** [comment]
Just to let you know, it worked with clinica 0.6.0
