### ISSUE TITLE
Index(...) must be called with a collection (create_adni_sessions_dict)

### ISSUE THREAD

**Issue by ConnorBehnen** [aramis-lab/clinica#730]
**Describe the bug**
I'm receiving the following error when trying to run any of my current subjects in the adni-to-bids converter:
"TypeError: Index(...) must be called with a collection of some kind, 'session_id' was passed"

**To Reproduce**
Subjects Used: 007_S_6255, 127_S_6549
1. Following the instructions at https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/
2. Command given: clinica convert adni-to-bids DATASET_DIRECTORY CLINICAL_DATA_DIRECTORY BIDS_DIRECTORY --subjects_list subjects.txt
3. See error:
`Traceback (most recent call last):
  File "/Users/cb/opt/anaconda3/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 134, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 723, in create_adni_sessions_dict
    df_filtered.dropna(subset="session_id", inplace=True)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 5950, in dropna
    indices = ax.get_indexer_for(subset)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5275, in get_indexer_for
    return self.get_indexer(target, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3437, in get_indexer
    target = self._maybe_cast_listlike_indexer(target)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5708, in _maybe_cast_listlike_indexer
    return ensure_index(target)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6336, in ensure_index
    return Index(index_like, copy=copy)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 474, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, 'session_id' was passed`

**Desktop:**
 - OS: Apple M1 - 12.4
 - Clinica Version - 0.7.2

**Additional context**
Looking at [adni_utils.py](https://github.com/aramis-lab/clinica/blob/dev/clinica/iotools/converters/adni_to_bids/adni_utils.py), line 723:
`df_filtered.dropna(subset="session_id", inplace=True)`
I believe subset should be passed a list (i.e. ["session_id"]) instead of a just a column name. I recreated this error with the basic example in the [pandas dropna docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html). I can make the bug fix, but I feel like I'm missing something as this line hasn't been changed in some time.

**Comment by NicolasGensollen** [comment]
Hi @ConnorBehnen and thanks for reporting.

Linking #634 where this was added.

Looking at the pandas dropna docs and code, I don't believe you're forced to provide a list. If you provide a column label alone, it will be casted to a list here:

 https://github.com/pandas-dev/pandas/blob/e8093ba372f9adfe79439d90fe74b0b5b6dea9d6/pandas/core/frame.py#L6000-L6003

What version of Pandas are you using?

**Comment by ghisvail** [comment]
> I recreated this error with the basic example in the [pandas dropna docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html).

According to the very same docs:

"subset : column label or sequence of labels, optional"

We are passing a column label, so we are compliant.

Could you confirm whether using a list or a set fixes this issue on your end?

**Comment by ghisvail** [comment]
Still from the same docs, running the examples:

```
>>> df = pd.DataFrame(
...    {
...        "name": ['Alfred', 'Batman', 'Catwoman'],
...        "toy": [np.nan, 'Batmobile', 'Bullwhip'],
...        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
...    }
... )
>>> df
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT
>>> df.dropna(subset="toy")
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT
```

**Comment by ghisvail** [comment]
It looks like a sequence [used to be required](https://github.com/pandas-dev/pandas/blob/3e89b4c4b1580aa890023fc550774e63d499da25/pandas/core/frame.py#L5071) for earlier versions of Pandas.

So either we raise the minimum version of Pandas from 1.2 to 1.4, or use a sequence, or maybe both actually. Pandas 1.4 supports Python 3.8 onwards, which is compatible with our support matrix.

**Comment by ghisvail** [comment]
I'd be in favour to raise the minimum version of Pandas. We have got no guarantees there aren't other nuggets of Pandas code elsewhere which are only compatible with 1.4 and we don't have enough coverage to chase them.

@ConnorBehnen just upgrade your version of Pandas to 1.4 in your Conda env and it should work.

**Comment by ghisvail** [comment]
We'll close this issue with the Pandas version bump.
