### ISSUE TITLE
error converting AIBL to BIDS

### ISSUE THREAD

**Issue by JiyangJiang** [aramis-lab/clinica#786]
Hi Clinica group,

I downloaded all AIBL MRI and PET (I clicked pre/post-processing tickboxes) from IDA, and clinical data from AIBL website.

I was trying to convert AIBL data to BIDS, but came across the following error. Any advice is much appreciated!

Many thanks,
Jiyang

+++++++++++++++++++++++++++++++++++++++++++++++++++

......
2022-11-10 21:30:22,062:INFO:Scans information for sub-AIBL1010 ses-M54 not found.
2022-11-10 21:30:22,063:INFO:Scans information for sub-AIBL1010 ses-M36 not found.
2022-11-10 21:30:22,064:INFO:Scans information for sub-AIBL108 ses-M18 not found.
2022-11-10 21:30:22,065:INFO:Scans information for sub-AIBL108 ses-M00 not found.
2022-11-10 21:30:22,066:INFO:Scans information for sub-AIBL108 ses-M54 not found.
2022-11-10 21:30:22,066:INFO:Scans information for sub-AIBL108 ses-M36 not found.
2022-11-10 21:30:22,067:INFO:Scans information for sub-AIBL1534 ses-M18 not found.
2022-11-10 21:30:22,068:INFO:Scans information for sub-AIBL1534 ses-M00 not found.
2022-11-10 21:30:22,069:INFO:Scans information for sub-AIBL1534 ses-M54 not found.
2022-11-10 21:30:22,069:INFO:Scans information for sub-AIBL1534 ses-M36 not found.
2022-11-10 21:30:22,070:INFO:Scans information for sub-AIBL1357 ses-M18 not found.
2022-11-10 21:30:22,071:INFO:Scans information for sub-AIBL1357 ses-M00 not found.
2022-11-10 21:30:22,072:INFO:Scans information for sub-AIBL1357 ses-M54 not found.
2022-11-10 21:30:22,073:INFO:Scans information for sub-AIBL1357 ses-M36 not found.
Traceback (most recent call last):
  File "/home/jiyang/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_to_bids_cli.py", line 48, in cli
    convert_clinical_data(bids_directory, clinical_data_directory)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_to_bids.py", line 66, in convert_clinical_data
    create_scans_dict_AIBL(bids_dir, path_to_csv, clinical_spec_path)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_utils.py", line 912, in create_scans_dict_AIBL
    scans_dict = bids.create_scans_dict(
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/bids_utils.py", line 404, in create_scans_dict
    file_to_read = pd.read_csv(
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 282, in read
    alldata = self._rows_to_cols(content)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 1045, in _rows_to_cols
    self._alert_malformed(msg, row_num + 1)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 765, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: Expected 36 fields in line 80, saw 37

**Comment by MatthieuJoulot** [comment]
Hi @JiyangJiang,

I would like to ask you for some more information ! Can you tell us the precise command you've used, with the eventual options ? Also, were you trying to convert a specific modality ?

I'll investigate in the meantime

**Comment by MatthieuJoulot** [comment]
After looking into it quickly, it appears that our clinical datas were old (2015) and that the latest is from 2018. However the csv downloaded through LONI are messed up on some lines (like line 80), and make the converter crash. It seems that on some of the lines there is an additional value. We will be looking to make our code more robust in this regard.

In the meantime, to make the converter work very quickly, I'd suggest you remove the excess values in `aibl_flutemeta_01-Jun-2018.csv`. There is about ten of them !

**Comment by ghisvail** [comment]
I just checked the content of the CSV and found this:

| RID | SITEID | VISCODE | PBCONDCT | EXAMDATE   | PBGE | PBGEMODEL | PBSIEMENS | PBSIEMODEL | PBPHILLIPS | PBPHMODEL | PBPIBTIME | PBPIBDOS | PBINJDOS | PBINJTIME | PBSCTIME | PBSTATDYN | PBNMFRAM1 | PBDURATN1 | PBMOTION | PBMOTSP | PBMALFUN | PBMALSP | PBOTHER | PBOTHSP | PBRECON | PBSUBSET | PBITERAT | PBRAMLA | PBFILTER | PBMODEON | PBSMOOTH | PBDECAY | PBSCATTR | PBMATTEN | PBTRSNFR                 |   |
|-----|--------|---------|----------|------------|------|-----------|-----------|------------|------------|-----------|-----------|----------|----------|-----------|----------|-----------|-----------|-----------|----------|---------|----------|---------|---------|---------|---------|----------|----------|---------|----------|----------|----------|---------|----------|----------|--------------------------|---|
| 618 | 1      | m18     | 1        | 08/06/2014 | -4   | -4        | 1         | 2          | -4         | -4        | -4        | -4       | 4.858    | 13:08:00  | 14:37:23 | 2         | -4        | 1200      | -4       | -4      | 0        | -4      | 1       | -4      | 4       | -4       | -4       | -4      | -4       | -4       | -4       | 1       | 1        | measured | AUSTIN AC CT Brain  H19s | 0 |

I don't think clipping the last column is gonna work to be honest.

All the buggy lines have this spurious value `measured,AUSTIN AC CT Brain  H19s` which contains a comma, hence the values being shifted by one column hereby confusing the parser.

**Comment by JiyangJiang** [comment]
Hi Matthieu and Ghislain,

Thanks for looking into this. I tried the following command to make it into one word

`sed -i 's/,measured,AUSTIN AC CT Brain  H19s,/,measured_AUSTIN_AC_CT_Brain_H19s,/' aibl_flutemeta_01-Jun-2018.csv`

i then ran 

`clinica convert aibl-to-bids raw/AIBL clinicalData/Data_extract_3.3.0 bids`

but i got the following error:

> """
Traceback (most recent call last):
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_utils.py", line 554, in create_file
    json_from_dcm(image_path, join(output_path, output_filename + ".json"))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/bids_utils.py", line 787, in json_from_dcm
    json = json.dumps(json_dict, skipkeys=True, indent=4)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiValue is not JSON serializable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiyang/miniconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_to_bids_cli.py", line 41, in cli
    convert_images(
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_to_bids.py", line 18, in convert_images
    paths_to_bids(
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/aibl_to_bids/aibl_utils.py", line 628, in paths_to_bids
    output_file_treated = pool.map(create_file_, images_list)
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jiyang/miniconda3/envs/clinicaEnv/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: Object of type MultiValue is not JSON serializable

**Comment by JiyangJiang** [comment]
I have version 2.3.0

# Name                    Version                   Build  Channel
pydicom                   2.3.0                    pypi_0    pypi

**Comment by ghisvail** [comment]
> sed -i 's/,measured,AUSTIN AC CT Brain H19s,/,measured_AUSTIN_AC_CT_Brain_H19s,/' aibl_flutemeta_01-Jun-2018.csv

This is probably not a good thing to do. This column is supposed to be numerical (an integer code to be exact) and we are turning it into something hybrid (numerical or text). I personnaly used `-4`, which is the code normally used for n/a values, and was able to progress further.

**Comment by ghisvail** [comment]
This particular error is fixed by #802 but other errors may happen further down the pipeline of the converter. Feel free to install the current version on `dev` and report other problems.
