### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'ns1'

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinica#913]
**Describe the bug**
Running adni-to-bids pipeline on T1w MRI data of ADNI and it is not resulting the relevant tsv files due to the value error
**To Reproduce**
1. In miniconda python 3.10 environment running clinica convert adni-to-bids /truba/repo/ALLADNI/MRI/ADNI/ /truba/home/meatay/clinical_adni/ /truba/home/meatay/ADNI_BIDS/
2. It creates the nifti folder structure
3. General tsv files like patients and modalities in the general bids folder but not the specific tsv files corresponding to the subjects which has the information about each sessions
4. See error, this is a huge log with many file pathways and the error is in the end of the log file which is easy to omit until the realization of missing subject tsv files.

[32m2023-05-15 02:56:39,553:INFO:Creating modality agnostic files...[0m
[32m2023-05-15 02:56:39,843:INFO:Creating participants.tsv...[0m
/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
[32m2023-05-15 02:56:44,174:INFO:The following subjects of dataset directory were not found in your BIDS folder :
070S4719, 098S4095, 003S6158, 005S6393, 153S6633, 153S6694, 114S6758, 016S6799, 012S6837, 305S6879, 021S6940, 027S6961, 021S6978, 341S6960, 341S6981, 024S7025, 341S7018, 037S6991, 035S7031, 035S7019, 037S7012, 011S7089, 053S7086[0m
/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py:446: PerformanceWarning: indexing past lexsort depth may impact performance.
  dxsum_df.loc[(alternative_id, "sc"), "DIAGNOSIS"].values[0]
[32m2023-05-15 02:56:44,619:INFO:Creating sessions files...[0m
[32m2023-05-15 02:56:44,652:INFO:	Reading clinical data file: ADNIMERGE.csv[0m
[32m2023-05-15 02:56:45,507:INFO:	Reading clinical data file: CDR.csv[0m
Traceback (most recent call last):
  File "/truba/home/meatay/miniconda3/envs/clinica/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 720, in create_adni_sessions_dict
    df_filtered["session_id"] = df_filtered.apply(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 721, in <lambda>
    lambda x: get_visit_id(x, location), axis=1
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 676, in get_visit_id
    return viscode_to_session(visit_id)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converter_utils.py", line 334, in viscode_to_session
    return "ses-" + f"M{(int(viscode[1:])):03d}"
ValueError: invalid literal for int() with base 10: 'ns1'

**Expected behavior**
Normally it should have convert the data into bids format without any errors.

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser : Firefox
 - Version : clinica 0.7.4, python 3.10, conda 23.3.1

**Comment by mselimata** [comment]
A side note: 
I tried on the different environment python 3.8 as suggested in the https://aramislab.paris.inria.fr/clinica/docs/public/latest/Installation/, clinica version 0.7.4 keeps not forming the tsv files.
And also I can confirm that in conda python 3.8 environment clinica version 0.7.3 on my copy of ADNI dataset successfully creates the BIDS folder with tsv files. 
It has a slight bug of lexsort which slows down the execution and lowers the resource management but works successfully: 
error log: /truba/home/meatay/miniconda3/envs/clinicaEnvo/lib/python3.8/site-packages/clinica/iotools/bids_util

s.py:104: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/miniconda3/envs/clinicaEnvo/lib/python3.8/site-packages/clinica/iotools/bids_utils.py:104: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.

  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/miniconda3/envs/clinicaEnvo/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py:446: PerformanceWarning: indexing past lexsort depth may impact performance.
  dxsum_df.loc[(alternative_id, "sc"), "DIAGNOSIS"].values[0] 
![Screenshot from 2023-05-15 09-13-16](https://github.com/aramis-lab/clinica/assets/17802601/393fa736-32f3-4b94-bc95-979c45c80e83)
![Screenshot from 2023-05-15 09-13-40](https://github.com/aramis-lab/clinica/assets/17802601/aa88bb08-f6f1-40c7-a687-856f2691441f)

**Comment by MatthieuJoulot** [comment]
Hi @mselimata, I'll look into it.

Looking at the screenshot you linked, I have a question: was your BIDS already partly generated ? The sessions are now supposed to be 3 digits long (`ses-M000` not `ses-M00`) or is it a screenshot of the BIDS you've generated with version `0.7.3` ?

Another question: how recent is the clinical data you are using ?

**Comment by mselimata** [comment]
Yes the last screenshot is from version 0.7.3

**Comment by ghisvail** [comment]
@mselimata so you're saying this is a regression introduced in version `0.7.4` since data and TSVs are successfully generated with version `0.7.3`, am I correct? 

@MatthieuJoulot interesting this parsing issue with `viscode`:

```python
>>> return "ses-" + f"M{(int(viscode[1:])):03d}"
ValueError: invalid literal for int() with base 10: 'ns1'
```

**Comment by mselimata** [comment]
Yes, exactly @NicolasGensollen

**Comment by MatthieuJoulot** [comment]
Looking at the clinical data, it seems that an error has been made for one subject, is `viscode` being `uns1`.

I have issued a [PR](https://github.com/aramis-lab/clinica/pull/914) that is supposed to be fixing this case. Do let us know if it fixes things for you.

**Comment by mselimata** [comment]
![Screenshot from 2023-05-15 23-43-43](https://github.com/aramis-lab/clinica/assets/17802601/c685e68c-a9ca-4158-afda-a81a8a152a01)
version 0.7.4 with the bugfixed PR, there seems like an another dependency in adni-utils.py is depending on converter-utils.py which is also triggering the same bug below:

/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
[32m2023-05-15 23:30:46,809:INFO:The following subjects of dataset directory were not found in your BIDS folder :
070S4719, 098S4095, 003S6158, 005S6393, 153S6633, 153S6694, 114S6758, 016S6799, 012S6837, 305S6879, 021S6940, 027S6961, 021S6978, 341S6960, 341S6981, 024S7025, 341S7018, 037S6991, 035S7031, 035S7019, 037S7012, 011S7089, 053S7086[0m
/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py:446: PerformanceWarning: indexing past lexsort depth may impact performance.
  dxsum_df.loc[(alternative_id, "sc"), "DIAGNOSIS"].values[0]
[32m2023-05-15 23:30:47,209:INFO:Creating sessions files...[0m
[32m2023-05-15 23:30:47,222:INFO:	Reading clinical data file: ADNIMERGE.csv[0m
[32m2023-05-15 23:30:48,079:INFO:	Reading clinical data file: CDR.csv[0m
Traceback (most recent call last):
  File "/truba/home/meatay/miniconda3/envs/clinica/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 720, in create_adni_sessions_dict
    df_filtered["session_id"] = df_filtered.apply(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 721, in <lambda>
    lambda x: get_visit_id(x, location), axis=1
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 676, in get_visit_id
    return viscode_to_session(visit_id)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/clinica/iotools/converter_utils.py", line 334, in viscode_to_session
    return "ses-" + f"M{(int(viscode[1:])):03d}"
ValueError: invalid literal for int() with base 10: 'ns1'

**Comment by NicolasGensollen** [comment]
Hi @mselimata 

It is weird that you still get this error since the fix contributed by @MatthieuJoulot in #914  🤔 

Could you pull again from the `dev` branch to get the latest additions and try running you code again ? 
Especially, you should also get #915 which is supposed to improve this error message (basically, the converter won't crash trying to cast something to an integer value but will tell you that the code it received isn't formatted properly and will explicitly tell you what it is expecting).

A few points to pay attention to:

- You can check that you have the latest fixes by doing a `git log` (make sure #914 and #915 are in there)
- Note also that you need to install Clinica from sources until we make a new patch release with these fixes

Let us know how it went !

**Comment by mselimata** [comment]
Thank you, I pulled as  you suggested a few minutes ago, @NicolasGensollen and checked the git log and both fix and enhancements are there.
Here is the error log as well as the folders without tsvs
![Screenshot from 2023-05-17 11-05-04](https://github.com/aramis-lab/clinica/assets/17802601/9b1d68ba-bff5-4292-ad03-5fff86632305)
![Screenshot from 2023-05-17 11-05-20](https://github.com/aramis-lab/clinica/assets/17802601/2e48ce55-b731-403d-84fb-5ad1851803d4)
[32m2023-05-17 10:48:27,202:INFO:Creating modality agnostic files...[0m
[32m2023-05-17 10:48:27,285:INFO:Creating participants.tsv...[0m
/truba/home/meatay/clinica/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/clinica/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
[32m2023-05-17 10:48:31,778:INFO:The following subjects of dataset directory were not found in your BIDS folder :
070S4719, 098S4095, 003S6158, 005S6393, 153S6633, 153S6694, 114S6758, 016S6799, 305S6879, 021S6940, 027S6961, 021S6978, 341S6960, 341S6981, 024S7025, 341S7018, 037S6991, 035S7031, 035S7019, 037S7012, 011S7089, 035S7121[0m
/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_utils.py:446: PerformanceWarning: indexing past lexsort depth may impact performance.
  dxsum_df.loc[(alternative_id, "sc"), "DIAGNOSIS"].values[0]
[32m2023-05-17 10:48:32,122:INFO:Creating sessions files...[0m
[32m2023-05-17 10:48:32,127:INFO:	Reading clinical data file: ADNIMERGE.csv[0m
[32m2023-05-17 10:48:33,016:INFO:	Reading clinical data file: CDR.csv[0m
[32m2023-05-17 10:48:33,315:INFO:	Reading clinical data file: NEUROBAT.csv[0m
[32m2023-05-17 10:48:33,805:INFO:	Reading clinical data file: ADASSCORES.csv[0m
Traceback (most recent call last):
  File "/truba/home/meatay/miniconda3/envs/clinica/bin/clinica", line 6, in <module>
    sys.exit(main())
  File "/truba/home/meatay/clinica/clinica/cmdline.py", line 92, in main
    cli()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 720, in create_adni_sessions_dict
    df_filtered["session_id"] = df_filtered.apply(
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/frame.py", line 9555, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 746, in apply
    return self.apply_standard()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 873, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/truba/home/meatay/miniconda3/envs/clinica/lib/python3.10/site-packages/pandas/core/apply.py", line 889, in apply_series_generator
    results[i] = self.f(v)
  File "/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 721, in <lambda>
    lambda x: get_visit_id(x, location), axis=1
  File "/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 676, in get_visit_id
    return viscode_to_session(visit_id)
  File "/truba/home/meatay/clinica/clinica/iotools/converter_utils.py", line 371, in viscode_to_session
    raise ValueError(
ValueError: The viscode uns1 is not correctly formatted.Expected a session identifier of the form 'MXXX', or a baseline identifier among {'bl', 'm0'}.

**Comment by NicolasGensollen** [comment]
@mselimata could you try again pulling from dev to get fix #920 from @MatthieuJoulot and re-run your code ?

**Comment by mselimata** [comment]
It works!  Thank you very much for solving very quickly. 
Both participants.tsv and subject tsv files are created in the corresponding folders.
here is the last part of the log, there is no error.
2023-05-18 00:41:30,224:INFO:Creating modality agnostic files...
2023-05-18 00:41:30,301:INFO:Creating participants.tsv...
/truba/home/meatay/clinica/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/truba/home/meatay/clinica/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
2023-05-18 00:41:34,780:INFO:The following subjects of dataset directory were not found in your BIDS folder :
070S4719, 098S4095, 003S6158, 005S6393, 153S6633, 153S6694, 114S6758, 016S6799, 305S6879, 021S6940, 027S6961, 021S6978, 341S6960, 341S6981, 024S7025, 341S7018, 037S6991, 035S7031, 035S7019, 037S7012, 011S7089, 035S7121
/truba/home/meatay/clinica/clinica/iotools/converters/adni_to_bids/adni_utils.py:446: PerformanceWarning: indexing past lexsort depth may impact performance.
  dxsum_df.loc[(alternative_id, "sc"), "DIAGNOSIS"].values[0]
2023-05-18 00:41:35,138:INFO:Creating sessions files...
2023-05-18 00:41:35,143:INFO:	Reading clinical data file: ADNIMERGE.csv
2023-05-18 00:41:36,060:INFO:	Reading clinical data file: CDR.csv
2023-05-18 00:41:36,383:INFO:	Reading clinical data file: NEUROBAT.csv
2023-05-18 00:41:36,867:INFO:	Reading clinical data file: ADASSCORES.csv
2023-05-18 00:41:37,031:INFO:	Reading clinical data file: CCI.csv
2023-05-18 00:41:37,189:INFO:	Reading clinical data file: ECOGPT.csv
2023-05-18 00:41:37,555:INFO:	Reading clinical data file: ECOGSP.csv
2023-05-18 00:41:37,963:INFO:	Reading clinical data file: FCI.csv
2023-05-18 00:41:38,280:INFO:	Reading clinical data file: GDSCALE.csv
2023-05-18 00:41:38,767:INFO:	Reading clinical data file: MODHACH.csv
2023-05-18 00:41:39,063:INFO:	Reading clinical data file: MOCA.csv
2023-05-18 00:41:39,551:INFO:	Reading clinical data file: NPI.csv
2023-05-18 00:41:40,244:INFO:	Reading clinical data file: NPIQ.csv
2023-05-18 00:41:40,816:INFO:	Reading clinical data file: BHR_EVERYDAY_COGNITION.csv
2023-05-18 00:41:41,246:INFO:	Reading clinical data file: BHR_BASELINE_QUESTIONNAIRE.csv
2023-05-18 00:41:41,720:INFO:	Reading clinical data file: BHR_LONGITUDINAL_QUESTIONNAIRE.csv
2023-05-18 00:41:42,303:INFO:	Reading clinical data file: MEDHIST.csv
2023-05-18 00:41:42,937:INFO:	Reading clinical data file: VITALS.csv
2023-05-18 00:42:13,057:INFO:Creating scans files...

**Comment by mselimata** [comment]
Thank you very much all of you, I am now closing the issue.
