### ISSUE TITLE
T1-linear: error running t1-linear with --random_seed

### ISSUE THREAD

**Issue by camillebrianceau** [aramis-lab/clinica#939]
clinica in developer mode 0.7.4
last commit: "Release `0.7.5`", n° 55a352d37049d92fb2568e3dbae1726013b7e50e, Mon Jun 5

command line:  on OASIS-1 dataset
`clinica convert oasis-to-bids data/raw data/raw data/bids` --> working
`clinica run t1-linear data/bids data/caps --random_seed 42 -np 9 -tsv data/tsv_test.tsv` --> error only with random_seed option

**Error**
exception calling callback for <Future at 0x7f588a733f40 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 719, in _run_command
    result = self._interface.run(cwd=outdir, ignore_exception=True)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 389, in run
    self._check_version_requirements(self.inputs)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 316, in _check_version_requirements
    raise Exception(
Exception: Trait random_seed (RegistrationSynQuick) (version 2.2.0 < required 2.3.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 223, in result
    return _load_resultfile(
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /tmp/tmpxwy8_7x9/t1-linear/5dc84c7a5c4ae993416cbd47706bc7c9ce5355ef/antsRegistrationSynQuick/result_antsRegistrationSynQuick.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/network/lustre/iss02/aramis/users/camille.brianceau/miniconda3/envs/reproducible-repo/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
FileNotFoundError: /tmp/tmpxwy8_7x9/t1-linear/5dc84c7a5c4ae993416cbd47706bc7c9ce5355ef/antsRegistrationSynQuick/result_antsRegistrationSynQuick.pklz

**Comment by ghisvail** [comment]
> `Exception: Trait random_seed (RegistrationSynQuick) (version 2.2.0 < required 2.3.0)`

Looks like you're using a version of ANTs (2.2.0) which does not support setting the random seed (2.3.0).

Version 2.2.0 was released in May 2017, so an upgrade is long overdue at this point :-)
