### ISSUE TITLE
ADNI-to-BIDS problem with PET 

### ISSUE THREAD

**Issue by Ryurin** [aramis-lab/clinica#952]
Hello, 

I have some problem with ADNI-to-BIDS conversion with PET. All PET scans (AV45, Tau and FDG) aren't found by Clinica. 
I have the right structure and MRI, for example, don't have this problem. 

I investigate about this and I found that the image ID between PETQC and ADNI images and what clinica found don't match. For example, for one subject, all ADNI files and directory have 861977 and clinica have 869908 (for AV45 PET on subject 002_0413 with m132 viscode). I check every files that clinica uses to make paths to images but I don't find any traces of 869908, I don't understand why it is its Image ID. This one is an example but no PET is found on my test directory (with 5 subjects in ADNI 3). 

Can you help me about this please ? 

Bests !

**Comment by ghisvail** [comment]
Hi, thanks for reaching out to us 👍 

Could you give us a more details about how you downloaded the data? Did you use the LONI website? Which subjects and filters did you use when designing your collection prior to download?

Cheers.

**Comment by Ryurin** [comment]
Hello, 

It's not me who downloaded the data and my colleague who did isn't available. I will ask him next week but I know some information.  

Yes, LONI website was used for the download and original data from 5 subjects was chosen. We wanted to test Clinica with few complete subject from ADNI3 so only the 5 first subjects with all original images from ADNI3 were downloaded (not only PET but all scans available from different visits). Subjects are 002_S_0413, 002_S_1155, 002_S_1261, 002_S_1280 and 002_S_4213. 

Only PET scans have some problem to be found by Clinica. Others are found (except scans that Clinica don't run). 

If more information is needed about it (because I don't have more  about filters), I will comment when my colleague is back next week.

**Comment by Ryurin** [comment]
Hello ! I ask the question to my colleague and he said that he used LONI website, he chose ADNI3 and all modalities (MRI, DTI, PET, FMRI) and selected the five first subjects : 002_S_0413, 002_S_1155, 002_S_1261, 002_S_1280 and 002_S_4213. I don't know if it help you or not.

**Comment by anarnold08** [comment]
Hi, 
I have faced the same issue. I have downloaded all the ADNI3 PET data for the subject 002_S_1155 at age 68 from the LONI website. I have also downloaded the Clinical data accordingly to the Clinica documentation (see https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/).

 However, when I am running: clinica convert adni-to-bids /Users/an/Desktop/test_subject/ADNI-4/ /Users/an/Desktop/data/clinica_data/ /Users/an/Desktop/data/BIDS_Unique/ -sl /Users/an/Desktop/data/one-subject.txt -m PET_AMYLOID 

I will get the following output:

/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py:206: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  adni_merge = pd.read_csv(adni_merge_path)
2023-10-09 15:27:51,191:INFO:Loading a subjects lists provided by the user...
2023-10-09 15:27:51,193:INFO:Calculating paths of PIB PET images. Output will be stored in /Users/an/Desktop/data/BIDS_test/conversion_info/v0.
/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py:1220: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  images.loc[:, "Is_Dicom"] = pd.Series(is_dicom, index=images.index)
/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py:1221: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  images.loc[:, "Path"] = pd.Series(image_folders, index=images.index)
2023-10-09 15:27:51,234:INFO:Paths of PIB PET images found. Exporting images into BIDS ...
2023-10-09 15:27:51,257:INFO:Calculating paths of AV45 and Florbetaben PET images. Output will be stored in /Users/an/Desktop/data/BIDS_test/conversion_info/v0.
2023-10-09 15:27:51,320:INFO:No Amyloid image path found for subject 002_S_1155 in visit m48 with image ID 210997
2023-10-09 15:27:51,321:INFO:No Amyloid image path found for subject 002_S_1155 in visit m72 with image ID 357454
2023-10-09 15:27:51,323:INFO:No Amyloid image path found for subject 002_S_1155 in visit m96 with image ID 469354
2023-10-09 15:27:51,324:INFO:No Amyloid image path found for subject 002_S_1155 in visit m126 with image ID 856317
2023-10-09 15:27:51,325:INFO:No Amyloid image path found for subject 002_S_1155 in visit m150 with image ID 1169592
2023-10-09 15:27:51,327:INFO:Paths of AV45 and Florbetaben PET images found. Exporting images into BIDS ...
2023-10-09 15:27:52,288:INFO:Creating modality agnostic files...
2023-10-09 15:27:52,293:INFO:Creating participants.tsv...
/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/bids_utils.py:114: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  file_to_read = pd.read_csv(file_to_read_path)
2023-10-09 15:27:54,287:INFO:The following subjects of dataset directory were not found in your BIDS folder :
002S1155
2023-10-09 15:27:54,335:INFO:Creating sessions files...
2023-10-09 15:27:54,337:INFO:	Reading clinical data file: ADNIMERGE.csv
2023-10-09 15:27:54,505:INFO:	Reading clinical data file: CDR.csv
2023-10-09 15:27:54,538:INFO:	Reading clinical data file: NEUROBAT.csv
2023-10-09 15:27:54,626:INFO:	Reading clinical data file: ADASSCORES.csv
2023-10-09 15:27:54,638:INFO:	Reading clinical data file: CCI.csv
2023-10-09 15:27:54,643:INFO:	Reading clinical data file: ECOGPT.csv
2023-10-09 15:27:54,679:INFO:	Reading clinical data file: ECOGSP.csv
2023-10-09 15:27:54,716:INFO:	Reading clinical data file: FCI.csv
2023-10-09 15:27:54,732:INFO:	Reading clinical data file: GDSCALE.csv
2023-10-09 15:27:54,764:INFO:	Reading clinical data file: MODHACH.csv
2023-10-09 15:27:54,774:INFO:	Reading clinical data file: MOCA.csv
2023-10-09 15:27:54,806:INFO:	Reading clinical data file: NPI.csv
2023-10-09 15:27:54,877:INFO:	Reading clinical data file: NPIQ.csv
2023-10-09 15:27:54,903:INFO:	Reading clinical data file: BHR_EVERYDAY_COGNITION.csv
2023-10-09 15:27:54,907:INFO:	Reading clinical data file: BHR_BASELINE_QUESTIONNAIRE.csv
2023-10-09 15:27:54,909:INFO:	Reading clinical data file: BHR_LONGITUDINAL_QUESTIONNAIRE.csv
2023-10-09 15:27:54,912:INFO:	Reading clinical data file: MEDHIST.csv
2023-10-09 15:27:54,924:INFO:	Reading clinical data file: VITALS.csv
Traceback (most recent call last):
  File "/Users/an/anaconda3/envs/clinicaEnv/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/Users/an/anaconda3/envs/clinicaEnv/lib/python3.8/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 980, in create_adni_sessions_dict
    raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
ValueError: Empty dataset detected. Clinical data cannot be extracted.


How can the error: ValueError: Empty dataset detected. Clinical data cannot be extracted be resolved? 

Thank you very much for your answer!

**Comment by Ryurin** [comment]
Hello, to resolve this problem, I just download the PET scans without treatment and its works :)

**Comment by shaharEd** [comment]
Hi @Ryurin, could you explain what do you mean by "without treatment"? You mean you downloaded the PET-tau again?

**Comment by Ryurin** [comment]
Hello ! My colleague downloaded the PET again but with some process I guess. Clinica take can PET-tau (or others PET in the documentation) but it can't work if PET scans don't have the waited processing. You should verify your images and the documentation and download the good version of the PET-tau for Clinica. I hope it is more clear for you !

**Comment by shaharEd** [comment]
Thank you very much!
Could you elaborate what exactly "waited processing" mean?

**Comment by NicolasGensollen** [comment]
I'm going to close this issue as it seems to be resolved.
Feel free to reopen if still facing the described issue.
