### ISSUE TITLE
ADNI to BIDS "Clinical data cannot be extracted"

### ISSUE THREAD

**Issue by mondrus96** [aramis-lab/clinica#966]
Hi there,

I'm trying to use the adni to bids function, but I'm running into an issue with the clinical data. To give some context, I've followed the steps from the guide (https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/). I've downloaded all the csv files from the clinical data and saved it in "CLINICAL_DATA_DIRECTORY". I've also used a small batch of images (since I'm trying to get a minimum working example of the pipeline), the names of which I've saved in subjects.txt. For the images, I've tried downloaded all and placed them in the folder "ADNI" (original, pre-processed, post-processed). I'm using only MRI images at the moment. 

I run the following code from my terminal:

clinica convert adni-to-bids -sl subjects.txt -m T1 ADNI CLINICAL_DATA_DIRECTORY ADNI_BIDS

FYI - I've also tried different combinations of dropping the flags -sl and -m, as well as trying it on an external drive vs. internal storage.

Everything from the output log seems to run as expected, but once it gets to the clinical data, I get the following:

2023-09-07 23:34:29,790:INFO:   Reading clinical data file: ADNIMERGE.csv
2023-09-07 23:34:29,963:INFO:   Reading clinical data file: CDR.csv
2023-09-07 23:34:30,000:INFO:   Reading clinical data file: NEUROBAT.csv
2023-09-07 23:34:30,093:INFO:   Reading clinical data file: ADASSCORES.csv
2023-09-07 23:34:30,107:INFO:   Reading clinical data file: CCI.csv
2023-09-07 23:34:30,113:INFO:   Reading clinical data file: ECOGPT.csv
2023-09-07 23:34:30,152:INFO:   Reading clinical data file: ECOGSP.csv
2023-09-07 23:34:30,190:INFO:   Reading clinical data file: FCI.csv
2023-09-07 23:34:30,207:INFO:   Reading clinical data file: GDSCALE.csv
2023-09-07 23:34:30,240:INFO:   Reading clinical data file: MODHACH.csv
2023-09-07 23:34:30,250:INFO:   Reading clinical data file: MOCA.csv
2023-09-07 23:34:30,284:INFO:   Reading clinical data file: NPI.csv
2023-09-07 23:34:30,358:INFO:   Reading clinical data file: NPIQ.csv
2023-09-07 23:34:30,385:INFO:   Reading clinical data file: BHR_EVERYDAY_COGNITION.csv
2023-09-07 23:34:30,389:INFO:   Reading clinical data file: BHR_BASELINE_QUESTIONNAIRE.csv
2023-09-07 23:34:30,392:INFO:   Reading clinical data file: BHR_LONGITUDINAL_QUESTIONNAIRE.csv
2023-09-07 23:34:30,396:INFO:   Reading clinical data file: MEDHIST.csv
2023-09-07 23:34:30,408:INFO:   Reading clinical data file: VITALS.csv
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/clinica", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 147, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 845, in create_adni_sessions_dict
    raise ValueError("Empty dataset detected. Clinical data cannot be extracted.")
ValueError: Empty dataset detected. Clinical data cannot be extracted.

I've checked all of the csv files listed at the beginning of the log, and they are all present and non-empty.

My setup information:
M1 Macbook - OS 13.5.1 (22G90)
Python v3.11.3
Clinica v0.7.5
Conda v23.5.2

Any help would be greatly appreciated! Please let me know if you need more context to reproduce the error.

**Comment by NicolasGensollen** [comment]
Hi @mondrus96 

Thanks for reporting.
The error occurs at this line:

https://github.com/aramis-lab/clinica/blob/55a352d37049d92fb2568e3dbae1726013b7e50e/clinica/iotools/converters/adni_to_bids/adni_utils.py#L844-L845

because the session dataframe computed in this function ends up being empty for some reason.

I'm not sure why at the moment but since your logs are printing "Reading clinical data file: ..." and you don't have an error when reading them with pandas, I suspect that the issue is that the filtering by subject ID is not working as expected (i.e. removing all rows in the dataframes).

Something that you can try (I haven't tested it so there might be some tweaks to do...) is to open a python terminal at the root of the Clinica repo and run the following:

```python
>>> from os import path
>>> import pandas as pd
>>> from clinica.iotools.bids_utils import get_bids_subjs_list
>>> bids_path = "absolute path to the BIDS output directory"
>>> clinical_data_dir = "absolute path to your clinical data dir for ADNI"
>>> bids_ids = get_bids_subjs_list(bids_path)
>>> print(bids_ids)
>>> df = pd.read_csv("./clinica/iotools/data/clinical_specifications_adni_sessions.tsv", sep="\t")
>>> files = list(df["ADNI location"].unique())
>>> files = [x for x in files if not pd.isnull(x)]
>>> assert len(files) != 0
>>> empty = []
>>> for location in files:
...     location = location.split("/")[0]
...     df_file = pd.read_csv(path.join(clinical_data_dir, location),  dtype=str)
...     df_filtered = filter_subj_bids(df_file, location, bids_ids).copy()
...     empty.append(df_filtered.empty)
...
>>> print(empty)
```

If `empty` only contains `True` then the filtering is removing all data and the sessions dataframe ends up being empty. If that's the case, we will investigate further.

Let me know if you have troubles running the script above.

**Comment by mondrus96** [comment]
Hi @NicolasGensollen,

Thank you so much for your response, I really appreciate your help! I've tried running the code and ran into a couple small issues.

1) in the following line:
`df = pd.read_csv("./clinica/iotools/data/clinical_specifications_adni_sessions.tsv", sep="\t")`
I'm guessing this should point towards the clinica package right? I've changed it to the following so that it goes to the package directory:
```
import pkg_resources
package_path = pkg_resources.resource_filename('clinica', '')
df = pd.read_csv(package_path+"/iotools/data/clinical_specifications_adni_sessions.tsv", sep="\t")
```
Just wanted to double check and make sure this is correct?

2) in the following lines:
```
bids_ids = get_bids_subjs_list(bids_path)
print(bids_ids)
```
bids_ids is empty. But isn't bids_path populated with subjects AFTER the converter runs successfully? The folder is still empty on my end because the converter didn't finish (I'm assuming). Because bids_ids is empty, there is nothing that is being added to empty in the for loop later on in the code.

3) in the for loop in the code you suggested, I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/T7 Shield/clinica/CLINICAL_DATA_DIRECTORY/ITEM.csv'`
I checked the zip file I downloaded from ADNI, and couldn't find "ITEM.csv" anywhere. Is it possible it doesn't exist, or should I go back and check the zip file I downloaded from ADNI?

For the sake of completeness, here is the full output when I run the code:
```
>>> from os import path
>>> import pandas as pd
>>> from clinica.iotools.bids_utils import get_bids_subjs_list
>>> from clinica.iotools.converters.adni_to_bids.adni_utils import filter_subj_bids
>>> import pkg_resources
>>> bids_path = "/Volumes/T7 Shield/clinica/ADNI"
>>> clinical_data_dir = "/Volumes/T7 Shield/clinica/CLINICAL_DATA_DIRECTORY"
>>> bids_ids = get_bids_subjs_list(bids_path)
>>> print(bids_ids)
[]
>>> package_path = pkg_resources.resource_filename('clinica', '')
>>> df = pd.read_csv(package_path+"/iotools/data/clinical_specifications_adni_sessions.tsv", sep="\t")
>>> files = list(df["ADNI location"].unique())
>>> files = [x for x in files if not pd.isnull(x)]
>>> assert len(files) != 0
>>> empty = []
>>> for location in files:
...      location = location.split("/")[0]
...      df_file = pd.read_csv(path.join(clinical_data_dir, location),  dtype=str)
...      df_filtered = filter_subj_bids(df_file, location, bids_ids).copy()
...      empty.append(df_filtered.empty)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/T7 Shield/clinica/CLINICAL_DATA_DIRECTORY/ITEM.csv'
>>> print(empty)
[True, True]
```

**Comment by ghisvail** [comment]
It looks like `ITEM.csv` is no longer part of the clinical data. There is a `ITEM_DICT.csv` which is probably the associated data dictionary, but the actual ITEM metadata are gone. I have verified it on a download from mid. 2021. Our much older CI data still has got the file.

I would be surprised if that were the root cause of your problem, though. I suspect we would have had reports for failed conversions much sooner.

Did you make sure to download *all* files, i.e. original, pre-processed and post-processed? Similar conversion problems reported in the past were with users only downloading the original data, whilst the converter computes the optimal data to convert based on QC information from the clinical data (and they are often pre-processed).

**Comment by ghisvail** [comment]
> There is a ITEM_DICT.csv which is probably the associated data dictionary, but the actual ITEM metadata are gone. I have verified it on a download from mid. 2021.

Looks like the latest one no longer has `ITEM.csv`, nor `ITEM_dict.csv`.

**Comment by mondrus96** [comment]
Hi @ghisvail,

Thank you so much for your insight, it is all very helpful!

I tried re-downloading ALL the files (under "image types" - ie. original, pre-processed, and post-processed). Re-ran and still failed, but got a different error code this time:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/clinica", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/cmdline.py", line 92, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 154, in convert_clinical_data
    adni_utils.create_adni_scans_files(conversion_path, bids_subjs_paths)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 950, in create_adni_scans_files
    df = pd.read_csv(path.join(conversion_path, older_version, tsv_path), sep="\t")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 636, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

**Comment by mondrus96** [comment]
Guessing its to do with the pd.read_csv line - but I'm not sure what "conversion_path, older_version, tsv_path" are referring to

**Comment by ghisvail** [comment]
Did you ensure the target BIDS directory for the conversion was empty? Since you did a few trials before, I suspect it is not and the conversion info cache files are invalid somehow. Might as well just start afresh.

**Comment by mondrus96** [comment]
Got it working actually - was a problem with my drive again. Not sure why, the command only seems to run properly when I run it off my local drive, not my external drive. Either way, thanks so much for your help.

**Comment by ghisvail** [comment]
> Either way, thanks so much for your help.

You're very welcome. Don't hesitate to contact us for any issues with other pipelines.
